### PR TITLE
Fix unit tests failing with jQuery 1.10.0

### LINKED ISSUE #60: Unit tests fail with jQuery 1.10.0
Unit tests pass in jQuery 1.9.1 but fail in jQuery 1.10.0 (20/449 assertions failed).

You can see the actual vs expected results if you run the test index.html in a browser and look in the console.

We need to fix this in order to be able to upgrade jQuery in the future and still have ArteJS work.

This may also fix #36 (Update this project within jQuery api).

### PR DESCRIPTION
**Pull request by chriskwan**
Fixes #60 

Fixing the core code and/or unit tests in order to make the tests pass with jQuery 1.10.0.

### CODE REVIEW

**Comment by chriskwan** [comment]
These fix the test `jQuery-dom-cleanup.style: mergeSpanSiblingsWithEmptyTextNodeInTheMiddle` in jQuery 1.10 (and theoretically above, but need to test that later).

Failed assertions when using jQuery 1.10: **20/449 -> 17/449**

**Comment by chriskwan** [comment]
These fix test `createUnorderedListWithDivs` in jQuery 1.10.

NOTE: like the previous fixed test, it was failing because we were using `jQuery.is()` to filter on text nodes which is not supported after jQuery 1.10. We should refactor to not rely on `jQuery.is()`.

Failed assertions when using jQuery 1.10: **17/449 -> 10/449**

**Comment by chriskwan** [comment]
These fix test `wrapWithTwoSiblingLists` in jQuery 1.10.

NOTE: like the previous two fixed tests, it was failing because we were using `jQuery.is()` to filter on text nodes which is not supported after jQuery 1.10. We should refactor to not rely on `jQuery.is()`.

Failed assertions when using jQuery 1.10: **10/449 -> 4/449**

**Comment by chriskwan** [comment]
This fixes test ` rangy.rangy.blockElementApplier.blockSetSurround: unwrapWhole` (and a bunch of other rangy tests) in jQuery 1.10.

NOTE: like the previous fixed tests, it was failing because we were using `jQuery.is()` to filter on text nodes which is not supported after jQuery 1.10. We should refactor to not rely on `jQuery.is()`.

Failed assertions when using jQuery 1.10: **4/449 -> 0/449**  WOOOT :raised_hands:

**Comment by chriskwan** [comment]
Now, that the tests are passing with jQuery 1.10.0, we should refactor the duplicated logic.

**Comment by chriskwan** [comment]
I manually tested (hard-coded the dependency and ran `grunt`) these jQuery versions and they all passed:
`jquery-1.7.2.js"> `
`jquery-1.8.3.js"> `
`jquery-1.9.1.js"> `
`jquery-1.10.0.js">`
`jquery-1.10.2.js">`
`jquery-1.11.2.js">`
`jquery-2.0.0.js"> `
`jquery-2.0.3.js"> `
`jquery-2.1.0.js"> `
`jquery-2.1.3.js"> `

We will programmatically test these as part of #62.

File: Gruntfile.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ module.exports = function(grunt) {
                 src: [
                     "<%= concat.rangy.src %>",
                     "<%= concat.editor.src %>",
-                    "<%= concat.toolbar.src %>",
+                    "<%= concat.toolbar.src %>"
```
Comment (gshenar) [inline Gruntfile.js]: thanks for cleaning this stuff up

File: tests/lib/rangy-extensions/RichTextCommandApplier.UnitTests.js [hunk 2]
```diff
@@ -547,26 +534,25 @@ var simpleSelectionMultiCommandTestData = [
...
-            var options = {
-                commandName: "unorderedList",
-                applierTagName: "UL",
-                textArea: arte
-            };
-            $.Arte.RichTextCommandApplier.createAndExecute(options);
-        },
-        expectedContent: "<ul><li>1</li><li>2</li><li>3</li><li>4</li><li>5</li><li>6</li><li>7</li></ul>"
-    }, {
+    name: "createUnorderedListOnDivaster",
```
Comment (gshenar) [inline tests/lib/rangy-extensions/RichTextCommandApplier.UnitTests.js]: divaster lol

File: src/editor/lib/jquery-extensions/jquery-dom-cleanup.js [hunk 3]
```diff
@@ -487,7 +487,9 @@
      */
     var removeEmptyElements = function(jNodes) {
         // Exclude the <br/> and rangy selection marker spans
-        var emptyElements = jNodes.find(":empty").not("br").not(":rangySpan");
+        var emptyElements = jNodes.find(":empty").not("br").not(function(index, element) {
```
Comment (gshenar) [inline src/editor/lib/jquery-extensions/jquery-dom-cleanup.js]: do we need to worry at all about the ":empty" selector?

File: tests/lib/rangy-extensions/RichTextCommandApplier.UnitTests.js (hunk 2 above)
Comment (nsp37) [inline tests/lib/rangy-extensions/RichTextCommandApplier.UnitTests.js]: probably the greatest line thus far

**Comment by nsp37** [comment]
+1 lets merge

File: src/editor/lib/jquery-extensions/jquery-dom-cleanup.js (hunk 3 above)
Comment (chriskwan) [inline src/editor/lib/jquery-extensions/jquery-dom-cleanup.js]: `:empty` is a built-in jQuery pseudo so we're fine.

**Comment by chriskwan** [comment]
Thanks for the :+1:'s guys. Will merge.

File: src/editor/lib/jquery-extensions/jquery-dom-cleanup.js (hunk 3 above)
Comment (Wilto) [inline src/editor/lib/jquery-extensions/jquery-dom-cleanup.js]: Hi guys!

Not to swoop in with two cents, but `:empty` is a really costly jQuery selector performance-wise: it checks against `visibility: hidden`, `display: none`, `height: 0`, and `width: 0`, and so on. I don’t have context for this line, but if these elements are being hidden in a way you can predict it would be a lot quicker to test for that specifically—and if I’m missing a ton of context, totally ignore me!

Comment (chriskwan) [inline src/editor/lib/jquery-extensions/jquery-dom-cleanup.js]: Thanks for the insight Wilto. I think we might be okay for now since the places where we use `:empty` are scoped to a smaller set of elements. It's definitely something to consider though when we look to remove the dependency on jQuery in the future.
